[package]
name = "snapduel"
version = "0.1.0"
edition = "2021"
authors = ["Sanskriti Singh <sanskritiisinghh2404@gmail.com>"]
description = "SnapDuel — On-chain quick-draw betting game on Solana"
homepage = "https://github.com/sanskritisingh245"
repository = "https://github.com/sanskritisingh245"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "snapduel"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
