/**
 * SnapDuel — Solana Anchor Client (Backend)
 *
 * Wraps all 4 on-chain instructions so the Node.js backend can call them
 * without knowing Anchor internals.
 *
 * Author  : Sanskriti Singh <sanskritiisinghh2404@gmail.com>
 * GitHub  : https://github.com/sanskritisingh245
 *
 * Instructions exposed:
 *   topUp(playerPubkey)                         — called after player's wallet tx
 *   deductCredit(matchId, p1Pubkey, p2Pubkey)   — on match creation
 *   settleMatch(matchId, p1Pubkey, p2Pubkey, winnerPubkey) — on match end
 *   cancelMatch(matchId, p1Pubkey, p2Pubkey)    — on disconnect / timeout
 *
 * PDAs exported for off-chain reads:
 *   getTreasuryPda()
 *   getCreditsPda(walletPubkey)
 *   getEscrowPda(matchId)
 *   getLeaderboardPda(walletPubkey)
 */

'use strict';

const { Connection, PublicKey, SystemProgram } = require('@solana/web3.js');
const anchor = require('@coral-xyz/anchor');
const { loadBackendKeypair } = require('./keypair');
const path = require('path');
const fs = require('fs');

// ─── Config ───────────────────────────────────────────────────────────────────

const PROGRAM_ID = new PublicKey(
  process.env.SNAPDUEL_PROGRAM_ID ||
  'SNAPD1111111111111111111111111111111111111111'  // Replace after first deploy
);

const RPC_URL =
  process.env.SOLANA_RPC_URL ||
  'https://api.devnet.solana.com';

// ─── Constants (must match lib.rs) ───────────────────────────────────────────
const WAGER_LAMPORTS = BigInt(10_000_000);   // 0.01 SOL
const TOPUP_COST_LAMPORTS = BigInt(50_000_000); // 0.05 SOL
const CREDITS_PER_TOPUP = 5;
const RAKE_BPS = BigInt(500);                // 5%

// ─── Setup ────────────────────────────────────────────────────────────────────

let _program = null;

/**
 * Lazily initialises and returns the Anchor Program instance.
 * Reads the IDL from the build output (generated by `anchor build`).
 */
function getProgram() {
  if (_program) return _program;

  const authority = loadBackendKeypair();
  const connection = new Connection(RPC_URL, 'confirmed');

  // AnchorProvider requires a Wallet interface
  const wallet = new anchor.Wallet(authority);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
    preflightCommitment: 'confirmed',
  });

  // Load IDL — generated by `anchor build`, lives at target/idl/snapduel.json
  const idlPath = path.resolve(__dirname, '../../snapduel-program/target/idl/snapduel.json');
  if (!fs.existsSync(idlPath)) {
    throw new Error(
      `IDL not found at ${idlPath}.\n` +
      `Run "anchor build" inside snapduel-program/ first.`
    );
  }
  const idl = JSON.parse(fs.readFileSync(idlPath, 'utf8'));

  _program = new anchor.Program(idl, PROGRAM_ID, provider);
  return _program;
}

// ─── PDA Helpers ─────────────────────────────────────────────────────────────

function getTreasuryPda() {
  return PublicKey.findProgramAddressSync([Buffer.from('treasury')], PROGRAM_ID);
}

function getCreditsPda(walletPubkey) {
  const key = walletPubkey instanceof PublicKey ? walletPubkey : new PublicKey(walletPubkey);
  return PublicKey.findProgramAddressSync(
    [Buffer.from('credits'), key.toBuffer()],
    PROGRAM_ID
  );
}

/**
 * @param {string|Buffer} matchId — UUID string (e.g. "abc123...") or 16-byte Buffer
 */
function getEscrowPda(matchId) {
  const buf = matchIdToBuffer(matchId);
  return PublicKey.findProgramAddressSync(
    [Buffer.from('escrow'), buf],
    PROGRAM_ID
  );
}

function getLeaderboardPda(walletPubkey) {
  const key = walletPubkey instanceof PublicKey ? walletPubkey : new PublicKey(walletPubkey);
  return PublicKey.findProgramAddressSync(
    [Buffer.from('leaderboard'), key.toBuffer()],
    PROGRAM_ID
  );
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Converts a UUID string or hex string into a 16-byte Buffer.
 * Accepts:
 *   - "550e8400-e29b-41d4-a716-446655440000"  (standard UUID v4)
 *   - "550e8400e29b41d4a716446655440000"       (hex without dashes)
 *   - Buffer (passed through)
 */
function matchIdToBuffer(matchId) {
  if (Buffer.isBuffer(matchId)) return matchId;
  const hex = matchId.replace(/-/g, '');
  if (hex.length !== 32) throw new Error(`matchId must be a 16-byte UUID, got: ${matchId}`);
  return Buffer.from(hex, 'hex');
}

/** Convert a 16-byte Buffer into number[] for the Anchor instruction */
function matchIdToArray(buf) {
  return Array.from(buf);
}

// ─── On-chain Instructions ────────────────────────────────────────────────────

/**
 * top_up — NOT called by the backend.
 *
 * Players call this directly from their wallet (mobile app / Solana Playground).
 * The backend can verify credits by reading the PlayerCredits PDA after the tx.
 *
 * This is here for completeness and manual testing only.
 */
async function topUp(playerPubkeyStr) {
  const program = getProgram();
  const playerKey = new PublicKey(playerPubkeyStr);
  const [treasury] = getTreasuryPda();
  const [playerCredits] = getCreditsPda(playerKey);

  const tx = await program.methods
    .topUp()
    .accounts({
      player: playerKey,
      treasury,
      playerCredits,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  console.log(`[topUp] tx: ${tx}`);
  return tx;
}

/**
 * deductCredit — called by the backend when two players are matched.
 *
 * @param {string} matchId       — UUID v4 string from the backend DB
 * @param {string} p1PubkeyStr  — Player one's wallet pubkey (base58)
 * @param {string} p2PubkeyStr  — Player two's wallet pubkey (base58)
 * @returns {string} Transaction signature
 */
async function deductCredit(matchId, p1PubkeyStr, p2PubkeyStr) {
  const program = getProgram();
  const matchIdBuf = matchIdToBuffer(matchId);

  const p1 = new PublicKey(p1PubkeyStr);
  const p2 = new PublicKey(p2PubkeyStr);
  const [treasury] = getTreasuryPda();
  const [p1Credits] = getCreditsPda(p1);
  const [p2Credits] = getCreditsPda(p2);
  const [escrow] = getEscrowPda(matchIdBuf);

  const tx = await program.methods
    .deductCredit(matchIdToArray(matchIdBuf))
    .accounts({
      authority: program.provider.wallet.publicKey,
      playerOne: p1,
      playerTwo: p2,
      playerOneCredits: p1Credits,
      playerTwoCredits: p2Credits,
      treasury,
      matchEscrow: escrow,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  console.log(`[deductCredit] match=${matchId} tx=${tx}`);
  return tx;
}

/**
 * settleMatch — called by the backend after the winner is determined.
 *
 * @param {string} matchId        — UUID v4 string
 * @param {string} p1PubkeyStr   — Player one's wallet pubkey (base58)
 * @param {string} p2PubkeyStr   — Player two's wallet pubkey (base58)
 * @param {string} winnerPubkeyStr — Winner's wallet pubkey (base58)
 * @returns {string} Transaction signature
 */
async function settleMatch(matchId, p1PubkeyStr, p2PubkeyStr, winnerPubkeyStr) {
  const program = getProgram();
  const matchIdBuf = matchIdToBuffer(matchId);

  const p1 = new PublicKey(p1PubkeyStr);
  const p2 = new PublicKey(p2PubkeyStr);
  const winner = new PublicKey(winnerPubkeyStr);
  const [treasury] = getTreasuryPda();
  const [escrow] = getEscrowPda(matchIdBuf);
  const [p1Leaderboard] = getLeaderboardPda(p1);
  const [p2Leaderboard] = getLeaderboardPda(p2);

  const tx = await program.methods
    .settleMatch(winner)
    .accounts({
      authority: program.provider.wallet.publicKey,
      matchEscrow: escrow,
      winner,
      treasury,
      playerOneLeaderboard: p1Leaderboard,
      playerTwoLeaderboard: p2Leaderboard,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  console.log(`[settleMatch] match=${matchId} winner=${winnerPubkeyStr} tx=${tx}`);
  return tx;
}

/**
 * cancelMatch — called by the backend on disconnect / timeout / tie.
 *
 * @param {string} matchId        — UUID v4 string
 * @param {string} p1PubkeyStr   — Player one's wallet pubkey (base58)
 * @param {string} p2PubkeyStr   — Player two's wallet pubkey (base58)
 * @returns {string} Transaction signature
 */
async function cancelMatch(matchId, p1PubkeyStr, p2PubkeyStr) {
  const program = getProgram();
  const matchIdBuf = matchIdToBuffer(matchId);

  const p1 = new PublicKey(p1PubkeyStr);
  const p2 = new PublicKey(p2PubkeyStr);
  const [treasury] = getTreasuryPda();
  const [escrow] = getEscrowPda(matchIdBuf);
  const [p1Credits] = getCreditsPda(p1);
  const [p2Credits] = getCreditsPda(p2);

  const tx = await program.methods
    .cancelMatch()
    .accounts({
      authority: program.provider.wallet.publicKey,
      matchEscrow: escrow,
      treasury,
      playerOneCredits: p1Credits,
      playerTwoCredits: p2Credits,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  console.log(`[cancelMatch] match=${matchId} tx=${tx}`);
  return tx;
}

// ─── Off-chain Read Helpers ────────────────────────────────────────────────────

/**
 * Fetch a player's credit balance from the chain.
 * Returns null if the account doesn't exist yet (player hasn't topped up).
 */
async function getCredits(walletPubkeyStr) {
  try {
    const program = getProgram();
    const [creditsPda] = getCreditsPda(new PublicKey(walletPubkeyStr));
    const account = await program.account.playerCredits.fetch(creditsPda);
    return {
      playsRemaining: account.playsRemaining,
      totalToppedUp: account.totalToppedUp.toNumber(),
    };
  } catch {
    return null; // Account doesn't exist
  }
}

/**
 * Fetch a player's leaderboard stats from the chain.
 * Returns null if the player has never played a settled match.
 */
async function getLeaderboard(walletPubkeyStr) {
  try {
    const program = getProgram();
    const [lbPda] = getLeaderboardPda(new PublicKey(walletPubkeyStr));
    const account = await program.account.leaderboard.fetch(lbPda);
    return {
      wins: account.wins,
      losses: account.losses,
      elo: account.elo,
    };
  } catch {
    return null;
  }
}

/**
 * Fetch the current treasury balance in lamports.
 */
async function getTreasuryBalance() {
  const program = getProgram();
  const [treasury] = getTreasuryPda();
  const info = await program.provider.connection.getAccountInfo(treasury);
  return info ? BigInt(info.lamports) : 0n;
}

// ─── Exports ──────────────────────────────────────────────────────────────────

module.exports = {
  // Instructions
  topUp,
  deductCredit,
  settleMatch,
  cancelMatch,

  // Read helpers
  getCredits,
  getLeaderboard,
  getTreasuryBalance,

  // PDA derivation (useful for the frontend / verification)
  getTreasuryPda,
  getCreditsPda,
  getEscrowPda,
  getLeaderboardPda,

  // Constants
  WAGER_LAMPORTS,
  TOPUP_COST_LAMPORTS,
  CREDITS_PER_TOPUP,
  RAKE_BPS,
  PROGRAM_ID,
};
